### ISSUE TITLE
AutoRepar does not eliminate epsilon from expression correctly

### ISSUE THREAD

**Issue by MathiasTantau** [afvillaverde/strike-goldd#5] opened 2021-02-08 18:16 UTC
I tested the following model with states x_1 to x_4, parameters c1, d1, J, J2:
System function f =
[x_2;
(u_1 - c2*x_1 + c2*x_3 - d2*x_2 + d2*x_4)/J1;
x_4;
(c2*x_1 - c2*x_3 + d2*x_2 - d2*x_4)/J2];
Output function h = x_3;

AutoRepar returns the following reparameterization:
x_1 <-- x_3 + (J1*J2*(x_1 - x_3))/(J2^2 - J2 + J1*J2)
x_2 <-- x_4 + (J1*J2*(x_2 - x_4))/(J2^2 - J2 + J1*J2)
x_3 <-- x_3
x_4 <-- x_4
J1 <-- J1 + J2 - 1
J2 <-- 1
c2 <-- (c2*exp(-2*epsilon)*(J2^2 - J2 + J1*J2))/J1
d2 <-- (d2*exp(-2*epsilon)*(J2^2 - J2 + J1*J2))/J1
 Obviously, epsilon is not eliminated from the last two lines although it should be. Is there possibly a problem with replacing exp(epsilon) in the scaling symmetry case?

**Comment by afvillaverde** [comment] 2021-02-09 08:55
Thank you for informing of this issue. We have just updated the code to address the problem. Please check if the changes have solved it, and let us know of the outcome.

**Comment by afvillaverde** [comment] 2021-02-18 09:02
We have committed a new set of changes (#8), which improves the compatibility with different versions of the Matlab Symbolic Math Toolbox. I think the issue is now solved.

**Closed by afvillaverde** 2021-02-18 09:02 UTC
